# Generated by Django 5.1 on 2024-09-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app_pr1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmful_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('Harm_Level', models.CharField(choices=[('select', 'Select'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='select', max_length=10)),
            ],
            options={
                'db_table': 'Harmful_Ingredients',
            },
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_link', models.URLField()),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
    ]
